### ISSUE TITLE
Ability to have kiik configuration files

### ISSUE THREAD

**Issue by lucca65** [kiik-payments/kiik_ruby#5]
We need to be able to have a configuration file to read from, with env sensible configurations.

By default we must use a demonstration access key, and if that key is used, print that the http calls are in `DEMO MODE`.

This way is clear for the developers that he is using an test key, and easy to setup production, test, and development environments

**Comment by esdrasedu** [comment]
This way is cool, only bad is running 2 app the same env!

**Comment by esdrasedu** [comment]
pull request #8
